#!/bin/sh

set -e

lb config noauto \
   --architectures amd64 \
   --apt-secure false \
   --distribution sid \
   --mirror-bootstrap ftp://ftp.us.debian.org/debian/ \
   --apt-recommends true \
   --archive-areas "main contrib non-free" \
   --firmware-binary true \
   --firmware-chroot true \
   --binary-images iso-hybrid \
   --initsystem systemd \
   "${@}"
